import '@/global/global.scss';
import type { Metadata } from 'next';
import { PublicSans } from '@/global/fonts';
import { LOCALE } from '@/global/constants';
import Header from '@/components/global/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const revalidate = 10;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={LOCALE}>
      <body className={PublicSans.className}>
        <Header />
        <main id='main'>{children}</main>
      </body>
    </html>
  );
}
